name: junorno_news
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

    


  get: ^4.6.5







  device_preview: ^1.2.0
  flutter_quill: ^9.3.1
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  http: ^1.2.2
  dio: ^5.0.10  # Add the latest stable version of Dio
  path_provider: ^2.0.9
  open_file: ^3.2.1
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_secure_storage: ^8.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.9.2"





flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: PoppinsLight
      fonts:
        - asset:   assets/fonts/Poppins-Light.ttf

